//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MohsyWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDetail
    {
        public int PersonDetailsID { get; set; }
        public int UserDetailsID { get; set; }
        public string Religion { get; set; }
        public string Caste { get; set; }
        public string SubCaste { get; set; }
        public string EatingHabit { get; set; }
        public string Smoking { get; set; }
        public string DrinkType { get; set; }
        public string LifeStyle { get; set; }
        public string Hobbies { get; set; }
        public string EducationalQualificationId { get; set; }
        public string NameoftheInstitution { get; set; }
        public string Occupation { get; set; }
        public string Designation { get; set; }
        public string Income { get; set; }
        public string BusinessType { get; set; }
        public string Aboutmyself { get; set; }
        public string FamilyType { get; set; }
        public string FamilyValues { get; set; }
        public string FamilyStatus { get; set; }
        public string FamilyOrigin { get; set; }
        public string NoofSiblings { get; set; }
        public string NOofmarriedSiblings { get; set; }
        public string Fathersoccupation { get; set; }
        public string Mothersoccupation { get; set; }
        public string FamilyBusinesstype { get; set; }
        public string FamilyBusinessTenure { get; set; }
        public string AboutmyFamily { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Manglik { get; set; }
        public string HoroscopeAvailable { get; set; }
        public string Raasi { get; set; }
        public string Star { get; set; }
        public string Gothram { get; set; }
        public string Turnover { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
