//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MohsyWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int UserDetailsID { get; set; }
        public string FirstName { get; set; }
        public string MatrimonyId { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string BodyType { get; set; }
        public string Complexion { get; set; }
        public string PhysicalStatus { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string MaritalStatus { get; set; }
        public string NoofChildren { get; set; }
        public Nullable<int> MotherTongueId { get; set; }
        public string LanguagesKnown { get; set; }
        public Nullable<int> ResidingCountryId { get; set; }
        public string ResidingState { get; set; }
        public string ResidingCity { get; set; }
        public Nullable<int> CitizenshipId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Role { get; set; }
        public Nullable<bool> IsUpgraded { get; set; }
        public Nullable<int> UpgradeId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string MobileNo { get; set; }
    }
}
