//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MohsyWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public int ID { get; set; }
        public Nullable<int> UserDetailsID { get; set; }
        public Nullable<bool> WhoViewedProfile { get; set; }
        public Nullable<bool> NewMatchingProfile { get; set; }
        public Nullable<bool> WhoShortlistedMe { get; set; }
        public Nullable<bool> AllNotifications { get; set; }
        public Nullable<bool> SMSAlert { get; set; }
        public Nullable<bool> EmailAlert { get; set; }
        public Nullable<bool> RequestViewPhoto { get; set; }
        public Nullable<bool> PhotoVisibleonAcceptance { get; set; }
        public Nullable<bool> Visibletoall { get; set; }
        public string PhotoPassword { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> VisibleOnlytoSpecificMembers { get; set; }
        public Nullable<bool> ProtectPhotoPwdMode { get; set; }
    }
}
